= Mashapedia: Technologies of _Attack Surface_ by Cory Doctorow
:toc: left
:stylesdir: stylesheets/
:stylesheet: masha.css


== Introduction

I am a big fan of Cory Doctorow (link:https://twitter.com/doctorow[@doctorow]). 
Not only his books _Little Brother_, _Homeland_, and now _Attack Surface_
discuss important topics like online privacy and the role of technology in today`'s world,
but also they educate the readers by telling them stories about modern tech solutions and tools.
Doctorow usually doesn`'t give you a lot of explanations, assuming that you can
find all the necessary information if you want to.

When I started reading _Attack Surface_ I was amazed by the amount of tech terms Doctorow 
was using here and there. I thought about some terms: "`Okay, I know what '`Tor`' means, 
but does everybody else who is reading this book now?`". Other terms I had to google myself: "`What is IMSI-catcher?`" 

I thought it might be a good idea to collect all tech terms that _might_ be new to the readers
and give a quick explanation for each of them. 
Also a link or two to more detailed pages would be helpful.

This is my collection of _Attack Surface_ terms. 
Most of the time I give links to Wikipedia, sometimes to other resources.

If you want to add, correct, or expand some terms or add more interesting links,
feel free to open issues in my Github repo (https://github.com/pavelanni/attack-surface-tech) or fork it and and open a PR. 
I`'ll be happy to include your additions to this list.

* Cory Doctorow`'s page: https://craphound.com/
* _Attack Surface_ page: https://craphound.com/category/attacksurface/
* _Little Brother_ and _Homeland_ (two previous books of this trilogy): https://craphound.com/category/littlebrother/ and https://craphound.com/category/homeland/

Mashapedia link:attack-surface-tech.html[chapter-by-chapter].

Mashapedia sorted link:mashapedia-alphabetical.html[alphabetically].
